name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: Run pytest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        dbt-version: ["1.6.0", "1.7.0", "1.7.10", "1.8.0"]
        exclude:
          # only dbt >= 1.7.9 supports Python 3.12
          - python-version: 3.12
            dbt-version: 1.6.0
          - python-version: 3.12
            dbt-version: 1.7.0

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install dbt-core ${{ matrix.dbt-version }}
        run: |
          echo "Expected Python version: '${{ matrix.python-version }}'"
          poetry env use "${{ matrix.python-version }}"
          poetry run pip install "dbt-core==${{ matrix.dbt-version }}"
          CURRENT_PYTHON_VERSION=$(poetry run python --version 2>&1 | awk '{print $2}')
          echo "poetry created the environment using Python '$CURRENT_PYTHON_VERSION'."
          CURRENT_MAJOR_MINOR=$(echo "$CURRENT_PYTHON_VERSION" | grep -oE '[0-9]+\.[0-9]+' | head -n 1)
          if [[ "$CURRENT_MAJOR_MINOR" != "${{ matrix.python-version }}" ]]; then
            echo "Error: Expected Python version '${{ matrix.python-version }}' but poetry created an environment using '$CURRENT_PYTHON_VERSION'."
            exit 1
          fi

      - name: Install poetry environment
        run: |
          poetry run pip install .
          poetry install --only dev

      - name: Install required packages
        run: | # install duckdb extras to be able to parse manifest
          poetry run pip install ".[duckdb]"

      - name: Parse manifest
        run: |
          poetry run dbt parse --project-dir demo_duckdb --profiles-dir demo_duckdb -t test

      - name: Run pytest
        run: |
          poetry run python -m pytest

      - name: Test dbt-osmosis yaml
        run: |
          poetry run dbt-osmosis yaml refactor --project-dir demo_duckdb --profiles-dir demo_duckdb

      - name: Test dbt-osmosis workbench
        run: |
          poetry run pip install ."[workbench,duckdb]"
          nohup poetry run dbt-osmosis workbench --project-dir demo_duckdb --profiles-dir demo_duckdb > dbt-osmosis.log 2>&1 &
          SERVER_PID=$!
          sleep 10
          curl --fail http://localhost:8501 || { echo "Workbench is not running!"; exit 1; }
          kill $SERVER_PID
          cat dbt-osmosis.log
